kind: "CronJob"
apiVersion: "batch/v1"
metadata:
  name: {{ template "bcparks_etl_fullname" . }}
  labels:
    template: {{ template "bcparks_etl_fullname" . }}-cronjob
    cronjob: {{ template "bcparks_etl_fullname" . }}
spec:
  schedule: {{ .Values.etl.schedule }}
  concurrencyPolicy: "Forbid"
  suspend: {{ not .Values.etl.enabled }}
  successfulJobsHistoryLimit: {{ .Values.etl.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.etl.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        template: {{ template "bcparks_etl_fullname" . }}-job
        cronjob: {{ template "bcparks_etl_fullname" . }}
    spec:
      backoffLimit: {{ .Values.etl.backoffLimit }}
      template:
        metadata:
          labels:
            template: {{ template "bcparks_etl_fullname" . }}-job
            cronjob: {{ template "bcparks_etl_fullname" . }}
        spec:
          containers:
            - name: {{ template "bcparks_etl_fullname" . }}-cronjob
              image: {{ .Values.images.etl.name }}:{{ .Values.images.etl.tag }}
              resources:
{{ toYaml .Values.etl.resources | indent 16 }}
              imagePullPolicy: Always
              env:
                - name: BCWFS_BANS_API
                  value: {{ .Values.etl.env.bcwfsBansApi }}
                - name: PARK_NAMES_API
                  value: {{ .Values.etl.env.parkNamesApi }}
                - name: STRAPI_BASE_URL
                  value: {{ .Values.cms.env.externalUrl }}
                - name: STRAPI_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-{{ .Values.etl.componentName }}-secret
                      key: STRAPI_API_TOKEN
                - name: PARK_NAMES_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-{{ .Values.etl.componentName }}-secret
                      key: PARK_NAMES_API_KEY
                - name: DISABLE_BCWFS_CRON
                  value: {{ .Values.etl.disableBcwfsCron | quote }}
                - name: ENABLE_BCWFS_STANDALONE_PROPAGATION
                  value: {{ .Values.etl.enableBcwfsStandalonePropagation | quote }}
                - name: DISABLE_PARK_NAMES_CRON
                  value: {{ .Values.etl.disableParkNamesCron | quote }}
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 1600
          dnsPolicy: "ClusterFirst"