kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "bcparks_scheduler_fullname" . }}
  labels:
    component: {{ .Values.scheduler.componentName }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.scheduler.componentName }}
      release: {{ .Release.Name }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        component: {{ .Values.scheduler.componentName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.scheduler.componentName }}
          resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
          image: {{ .Values.images.scheduler.name }}:{{ .Values.images.scheduler.tag }}
          imagePullPolicy: {{ .Values.scheduler.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{ template "bcparks_elasticsearch_secret" . }}
          env:
            - name: STRAPI_BASE_URL
              value: {{ .Values.cms.env.externalUrl }}
            - name: STRAPI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.etl.componentName }}-secret
                  key: STRAPI_API_TOKEN
            - name: ELASTIC_PARK_INDEX_NAME
              value: {{ .Values.cms.env.indexName | quote }}
            - name: BCPARKS_ENVIRONMENT
              value: {{ .Values.cms.env.environment }}
            - name: BATCH_SIZE
              value: {{ .Values.scheduler.env.batchSize | quote }}
            - name: GEOSHAPE_URL
              value: {{ .Values.scheduler.env.shapeDataApi | quote }}
            - name: EMAIL_ENABLED
              value: {{ .Values.scheduler.env.emailEnabled | quote }}
            - name: EMAIL_SERVER
              value: {{ .Values.scheduler.env.emailServer }}
            - name: EMAIL_PORT
              value: {{ .Values.scheduler.env.emailPort | quote }}
            - name: EMAIL_SENDER
              value: {{ .Values.scheduler.env.emailSender }}
            - name: EMAIL_RECIPIENT
              value: {{ .Values.scheduler.env.emailRecipient | quote }}
            - name: PUBLIC_URL
              value: {{ .Values.cluster.publicUrl | quote }}
            - name: ADMIN_URL
              value: {{ .Values.cluster.staffPortalUrl | quote }}
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - health.sh
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 120
            successThreshold: 1
            failureThreshold: 3