kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: imagetag-pruner
  annotations:
    description: Image Tag Pruner  (images are build locally and pushed to here)
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}    
spec: {}
