cluster:
  ssoAuthUrl: https://dev.loginproxy.gov.bc.ca/auth
  publicUrl: https://dev.bcparks.ca
  staffPortalUrl: https://dev-staff.bcparks.ca

cms:
  env:
    environment: dev
    externalUrl: https://dev-cms.bcparks.ca

patroni:
  replicas: 1

scheduler:
  env:
    emailEnabled: true
    emailRecipient: manuji@oxd.com,mike@oxd.com
