cluster:
  ssoAuthUrl: https://dev.loginproxy.gov.bc.ca/auth
  publicUrl: https://alpha-dev.bcparks.ca
  staffPortalUrl: https://alpha-dev-staff.bcparks.ca

images:
  strapi:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/strapi-alpha
  admin:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/admin-alpha
  public:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/public-alpha
  maintenance:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/maintenance-alpha
  etl:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/etl-alpha
  scheduler:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/scheduler-alpha

cms:
  env:
    environment: alpha-dev
    externalUrl: https://alpha-dev-cms.bcparks.ca

patroni:
  replicas: 1

backup:
  enabled: false

  enironment:
    friendlyName: bcparks.ca CMS Postgres Backup [alpha-dev]

etl:
  enabled: false

scheduler:
  env:
    emailEnabled: true
    emailRecipient: manuji@oxd.com,mike@oxd.com
