{{- if .Values.pgbouncer.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.pgbouncer.componentName }}
  labels:
    component: {{ .Values.pgbouncer.componentName }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.pgbouncer.componentName }}
      release: {{ .Release.Name }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        component: {{ .Values.pgbouncer.componentName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.pgbouncer.componentName }}
          resources:
{{ toYaml .Values.pgbouncer.resources | indent 12 }}
          image: {{ .Values.images.pgbouncer.name }}:{{ .Values.images.pgbouncer.tag }}
          imagePullPolicy: {{ .Values.pgbouncer.imagePullPolicy }}
          ports:
            - name: {{ .Values.pgbouncer.service.portName }}
              containerPort: {{ .Values.pgbouncer.service.port }}
              protocol: TCP
          env:
            - name: PGBOUNCER_DEFAULT_POOL_SIZE
              value: {{ .Values.pgbouncer.env.defaultPoolSize | quote }}
            - name: PGBOUNCER_POOL_MODE
              value: {{ .Values.pgbouncer.env.poolMode }}
            - name: PGBOUNCER_MAX_CLIENT_CONN
              value: {{ .Values.pgbouncer.env.maxClientConn | quote }}
            - name: POSTGRESQL_HOST
              value: {{ template "bcparks_patroni_fullname" . }}
            - name: POSTGRESQL_PORT
              value: {{ .Values.patroni.service.port | quote }}
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_patroni_secret" . }}
                  key: app-db-username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_patroni_secret" . }}
                  key: app-db-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_patroni_secret" . }}
                  key: app-db-name
            - name: PGBOUNCER_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_patroni_secret" . }}
                  key: app-db-name
{{- end }}