kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.cms.componentName }}
  labels:
    component: {{ .Values.cms.componentName }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.cms.componentName }}
      release: {{ .Release.Name }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        component: {{ .Values.cms.componentName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.cms.componentName }}
          resources:
{{ toYaml .Values.cms.resources | indent 12 }}
          image: {{ .Values.images.strapi.name }}:{{ .Values.images.strapi.tag }}
          imagePullPolicy: {{ .Values.cms.imagePullPolicy }}
          ports:
            - name: {{ .Values.cms.service.portName }}
              containerPort: {{ .Values.cms.service.port }}
              protocol: TCP
          env:            
            - name: NODE_ENV
              value: {{ .Values.cms.env.nodeEnv }}
            - name: STRAPI_TELEMETRY_DISABLED
              value: "true"
            - name: STRAPI_SSO_AUTH_URL
              value: {{ .Values.cluster.ssoAuthUrl }}
            - name: STRAPI_SSO_REALM
              value: {{ .Values.cluster.ssoRealm }}
            - name: STRAPI_EXTERNAL_URL
            {{- if .Values.cms.env.externalUrl }}
              value: {{ .Values.cms.env.externalUrl }}
            {{- else }}
              value: {{ template "bcparks_cms_external_url" . }}
            {{- end }}
            - name: DATABASE_CLIENT
              value: postgres
            - name: DATABASE_HOST
            {{- if .Values.pgbouncer.enabled }}
              value: {{ template "bcparks_pgbouncer_fullname" . }} 
            {{- else }}
              value: {{ template "bcparks_patroni_fullname" . }}
            {{- end }}
            - name: DATABASE_PORT
            {{- if .Values.pgbouncer.enabled }}
              value: {{ .Values.pgbouncer.service.port | quote }}
            {{- else }}
              value: {{ .Values.patroni.service.port | quote }}
            {{- end }}              
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_patroni_secret" . }}
                  key: app-db-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_patroni_secret" . }}
                  key: app-db-password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_patroni_secret" . }}
                  key: app-db-name
            - name: DATABASE_SSL
              value: "false"
            - name: DATABASE_MIN_CONNECTIONS
              value: {{ .Values.cms.env.databaseMinConnections | quote }}
            - name: DATABASE_MAX_CONNECTIONS
              value: {{ .Values.cms.env.databaseMaxConnections | quote }}
            - name: DATABASE_IDLE_TIMEOUT
              value: {{ .Values.cms.env.databaseIdleTimeout | quote }}
            - name: DATABASE_CREATE_TIMEOUT
              value: {{ .Values.cms.env.databaseCreateTimeout | quote }}
            - name: DATABASE_ACQUIRE_TIMEOUT
              value: {{ .Values.cms.env.databaseAcquireTimeout | quote }}
            - name: STRAPI_SMTP_HOST
              value: {{ .Values.cms.env.smtpHost }}
            - name: STRAPI_SMTP_PORT
              value: {{ .Values.cms.env.smtpPort | quote }}
            - name: STRAPI_SMTP_FROM
              value: {{ .Values.cms.env.smtpFrom }}
            - name: STRAPI_SMTP_REPLY_TO
              value: {{ .Values.cms.env.smtpReplyTo }}
          envFrom:
            - secretRef:
                name: {{ template "bcparks_cms_secret" . }}
            - secretRef:
                name: bcparks-object-storage
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.cms.service.portName }}
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 20
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.cms.service.portName }}
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 20
