name: Build CMS on main branch

on:
  push:
    branches:
      - main
    paths:
      - src/cms/**

env:
  IMAGE_NAME: strapi
  BUILDER_IMAGE: registry.access.redhat.com/ubi8/nodejs-14:1-43

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Set vars
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Login to OpenShift Container Repository
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}
      - name: s2i Build
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: "src/cms"
          builder_image: ${{ env.BUILDER_IMAGE }}
          image: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT_LICENSE_PLATE }}-tools/${{ env.IMAGE_NAME }}
      - name: Push Docker image
        run: docker push ${{ steps.build_image.outputs.image }}:latest
